/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as ScreenerRouteImport } from './routes/screener'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as QualityReviewRouteImport } from './routes/quality-review'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as EmployerRouteImport } from './routes/employer'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnnotationRouteImport } from './routes/annotation'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenerRoute = ScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityReviewRoute = QualityReviewRouteImport.update({
  id: '/quality-review',
  path: '/quality-review',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRoute = EmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnotationRoute = AnnotationRouteImport.update({
  id: '/annotation',
  path: '/annotation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/annotation': typeof AnnotationRoute
  '/auth': typeof AuthRoute
  '/consent': typeof ConsentRoute
  '/employer': typeof EmployerRoute
  '/how-it-works': typeof HowItWorksRoute
  '/jobs': typeof JobsRoute
  '/journey': typeof JourneyRoute
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRoute
  '/passport': typeof PassportRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/quality-review': typeof QualityReviewRoute
  '/results': typeof ResultsRoute
  '/screener': typeof ScreenerRoute
  '/test': typeof TestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/annotation': typeof AnnotationRoute
  '/auth': typeof AuthRoute
  '/consent': typeof ConsentRoute
  '/employer': typeof EmployerRoute
  '/how-it-works': typeof HowItWorksRoute
  '/jobs': typeof JobsRoute
  '/journey': typeof JourneyRoute
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRoute
  '/passport': typeof PassportRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/quality-review': typeof QualityReviewRoute
  '/results': typeof ResultsRoute
  '/screener': typeof ScreenerRoute
  '/test': typeof TestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/annotation': typeof AnnotationRoute
  '/auth': typeof AuthRoute
  '/consent': typeof ConsentRoute
  '/employer': typeof EmployerRoute
  '/how-it-works': typeof HowItWorksRoute
  '/jobs': typeof JobsRoute
  '/journey': typeof JourneyRoute
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRoute
  '/passport': typeof PassportRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/quality-review': typeof QualityReviewRoute
  '/results': typeof ResultsRoute
  '/screener': typeof ScreenerRoute
  '/test': typeof TestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/annotation'
    | '/auth'
    | '/consent'
    | '/employer'
    | '/how-it-works'
    | '/jobs'
    | '/journey'
    | '/leaderboard'
    | '/onboarding'
    | '/passport'
    | '/payment'
    | '/profile'
    | '/quality-review'
    | '/results'
    | '/screener'
    | '/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/annotation'
    | '/auth'
    | '/consent'
    | '/employer'
    | '/how-it-works'
    | '/jobs'
    | '/journey'
    | '/leaderboard'
    | '/onboarding'
    | '/passport'
    | '/payment'
    | '/profile'
    | '/quality-review'
    | '/results'
    | '/screener'
    | '/test'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/annotation'
    | '/auth'
    | '/consent'
    | '/employer'
    | '/how-it-works'
    | '/jobs'
    | '/journey'
    | '/leaderboard'
    | '/onboarding'
    | '/passport'
    | '/payment'
    | '/profile'
    | '/quality-review'
    | '/results'
    | '/screener'
    | '/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnnotationRoute: typeof AnnotationRoute
  AuthRoute: typeof AuthRoute
  ConsentRoute: typeof ConsentRoute
  EmployerRoute: typeof EmployerRoute
  HowItWorksRoute: typeof HowItWorksRoute
  JobsRoute: typeof JobsRoute
  JourneyRoute: typeof JourneyRoute
  LeaderboardRoute: typeof LeaderboardRoute
  OnboardingRoute: typeof OnboardingRoute
  PassportRoute: typeof PassportRoute
  PaymentRoute: typeof PaymentRoute
  ProfileRoute: typeof ProfileRoute
  QualityReviewRoute: typeof QualityReviewRoute
  ResultsRoute: typeof ResultsRoute
  ScreenerRoute: typeof ScreenerRoute
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screener': {
      id: '/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof ScreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality-review': {
      id: '/quality-review'
      path: '/quality-review'
      fullPath: '/quality-review'
      preLoaderRoute: typeof QualityReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer': {
      id: '/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof EmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annotation': {
      id: '/annotation'
      path: '/annotation'
      fullPath: '/annotation'
      preLoaderRoute: typeof AnnotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnnotationRoute: AnnotationRoute,
  AuthRoute: AuthRoute,
  ConsentRoute: ConsentRoute,
  EmployerRoute: EmployerRoute,
  HowItWorksRoute: HowItWorksRoute,
  JobsRoute: JobsRoute,
  JourneyRoute: JourneyRoute,
  LeaderboardRoute: LeaderboardRoute,
  OnboardingRoute: OnboardingRoute,
  PassportRoute: PassportRoute,
  PaymentRoute: PaymentRoute,
  ProfileRoute: ProfileRoute,
  QualityReviewRoute: QualityReviewRoute,
  ResultsRoute: ResultsRoute,
  ScreenerRoute: ScreenerRoute,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
